version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_DEPLOYMENT_MODE=${NEXT_PUBLIC_DEPLOYMENT_MODE:-self-hosted}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-3000}:3000"  # Use HOST_PORT env var, default to 3000
    volumes:
      # Only mount the data directory for database persistence
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/warranty.db
      - DEBUG_LOGS=${DEBUG_LOGS:-false}  # Enable debug logging when set to true
    restart: unless-stopped
    command: node .next/standalone/server.js 